demo_real_estate/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from demo_real_estate import settings

handler404 = "real_estate.views.custom_404"
handler500 = "real_estate.views.custom_500"

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('dashboard_admin_real_estate/', admin.site.urls),
    path('', include('real_estate.urls', namespace='en'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('real_estate.urls', namespace="ar")),
)

real_estate/urls.py
from django.urls import path

from real_estate import views

app_name = 'real_estate'

urlpatterns = [
    path('', views.home, name="main_home"),
    path('one_property/<uuid:uuid_property>/', views.get_single_property, name="one_property"),

]

real_estate/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# Create your models here.

class TblCustomUser(AbstractUser):
    phone_number = models.IntegerField(verbose_name=_('Phone Number')),

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')


class TblTypeProperty(models.Model):
    name_type_property = models.CharField(verbose_name=_('Name Type Property'), max_length=250)

    def __str__(self):
        return self.name_type_property

    class Meta:
        verbose_name = _('Type Property')
        verbose_name_plural = _('Types Properties')


class TblPropertyFor(models.Model):
    property_for = models.CharField(verbose_name=_('Property For'), max_length=250)

    def __str__(self):
        return self.property_for

    class Meta:
        verbose_name = _('Property For')
        verbose_name_plural = _('Properties For')


class TblPropertyCountry(models.Model):
    property_country = models.CharField(verbose_name=_('Property Country'), max_length=250)

    def __str__(self):
        return self.property_country

    class Meta:
        verbose_name = _('Property Country')
        verbose_name_plural = _('Properties Country')


class TblPropertyCity(models.Model):
    property_city = models.CharField(verbose_name=_('Property City'), max_length=250)

    def __str__(self):
        return self.property_city

    class Meta:
        verbose_name = _('Property City')
        verbose_name_plural = _('Properties City')


class TblPropertyListing(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title_property = models.CharField(verbose_name=_('Title Property'), max_length=250)
    image_property = models.ImageField(upload_to="images/property_listing", verbose_name=_('Image Property'))
    location_property = models.TextField()
    country_property = models.OneToOneField(TblPropertyCountry, on_delete=models.CASCADE, verbose_name=_("Country Property"),)
    city_property = models.OneToOneField(TblPropertyCity, on_delete=models.CASCADE, verbose_name=_("City Property"),)
    property_type = models.OneToOneField(TblTypeProperty, on_delete=models.CASCADE, verbose_name=_("Property Type"))
    property_for = models.ForeignKey(TblPropertyFor, on_delete=models.CASCADE, verbose_name=_("Property For"))
    size_property = models.IntegerField(verbose_name=_("Size Property"))
    beds_property = models.IntegerField(verbose_name=_("Beds Property"))
    bath_property = models.IntegerField(verbose_name=_("Bath Property"))
    price_property = models.DecimalField(verbose_name=_("Price Property"), max_digits=6, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title_property

    class Meta:
        verbose_name = _('Property Listing')
        verbose_name_plural = _('Properties Listing')


class TblPropertyImages(models.Model):
    property_title = models.ForeignKey(TblPropertyListing, related_name='images', on_delete=models.CASCADE)
    images_property = models.FileField(upload_to="images/property_listing", verbose_name=_('Images Property'))

    class Meta:
        verbose_name = _('Property Image')
        verbose_name_plural = _('Properties Images')

real_estate/views.py
from django.shortcuts import render
import logging

from real_estate.models import *

# Create your views here.
logger = logging.getLogger('real_estate')


def home(request):
    logger.debug('Performing operation...')
    get_all_property_listing = TblPropertyListing.objects.all()
    get_city_property = TblPropertyCity.objects.all()
    get_type_property = TblTypeProperty.objects.all()
    context = {
        'all_property_listing': get_all_property_listing,
        'all_property_city': get_city_property,
        'all_property_type': get_type_property,
    }
    return render(request, 'real_estate/main/home.html', context)


def get_single_property(request, uuid_property):
    get_one_property = TblPropertyListing.objects.get(id=uuid_property)
    get_all_images_property = TblPropertyImages.objects.filter(property_title__id=uuid_property)

    context = {
        'getOneProperty': get_one_property,
        'getAllImagesProperty': get_all_images_property,
    }

    return render(request, 'real_estate/main/one_property.html', context)


def custom_404(request, excption):
    return render(request, 'real_estate/page_not_found/404.html', status=404)


def custom_500(request):
    return render(request, 'real_estate/page_not_found/404.html')

templates/real_estate/footer/footer.html
{% load i18n %}
{% load static %}

<!-- Footer Start -->
<div class="container-fluid bg-brown text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s" >
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">{% translate 'Get In Touch' %}</h5>
                <p class="mb-2 text-white"><i class="fa fa-map-marker-alt m-2 text-white"></i>{% translate '123 Street, New York, USA' %}</p>
                <p class="mb-2 text-white"><i class="fa fa-phone-alt m-2 text-white"></i>{% translate '+012 345 67890' %}</p>
                <p class="mb-2 text-white"><i class="fa fa-envelope m-1 text-white"></i>{% translate 'info@example.com' %}</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6" dir="rtl">
                <h5 class="text-white mb-4">{% translate 'Quick Links' %}</h5>
                <a class="btn text-white" href="">{% translate 'About Us' %}</a>
                <a class="btn text-white" href="">{% translate 'Contact Us' %}</a>
                <a class="btn text-white" href="">{% translate 'Our Services' %}</a>
                <a class="btn text-white" href="">{% translate 'Privacy Policy' %}</a>
                <a class="btn text-white" href="">{% translate 'Terms & Condition' %}</a>
            </div>

            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">{% translate 'Newsletter' %}</h5>
                <p class="text-white">{% translate 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.' %}</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-gold py-2 position-absolute top-0 end-0 mt-2 m-2">{% translate 'SignUp' %}</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="{% url 'real_estate:main_home' %}">{% translate 'Riyadh Oasis' %}</a>{% translate ', All Right Reserved.' %}
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">{% translate 'Home' %}</a>
                        <a href="">{% translate 'Cookies' %}</a>
                        <a href="">{% translate 'Help' %}</a>
                        <a href="">{% translate 'FQAs' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

templates/real_estate/main/index.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
<html dir="auto" lang="auto">


<head>
    <meta charset="utf-8">
    <title>{% block titlePage %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="{% translate 'Riyadh Oasis Real Estate, Riyadh properties, Riyadh real estate agents, Riyadh homes for sale, Riyadh apartments for rent, Riyadh commercial properties, buy property in Riyadh, sell property in Riyadh, Riyadh real estate market, luxury homes Riyadh, Riyadh property listings, Riyadh real estate services' %}" name="keywords">
    <meta content="{% translate 'Riyadh Oasis Real Estate offers premium property listings in Riyadh, including residential and commercial properties, apartments, and luxury homes. Our expert real estate agents are dedicated to helping you buy, sell, or rent the perfect property in Riyadh. Explore the vibrant real estate market with us today' %}" name="description">

    <!-- Favicon -->
    <link href="{% static 'assets/img/logo/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'assets/lib/animate/animate.min.css' %} " rel="stylesheet">
    <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %} " rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'assets/css/bootstrap.min.css' %} " rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'assets/css/style.css' %} " rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">

        {% include 'real_estate/navbar/navbar.html' %}

        {% block content %}

        {% endblock %}

        {% include 'real_estate/footer/footer.html' %}

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assets/lib/wow/wow.min.js' %} "></script>
    <script src="{% static 'assets/lib/easing/easing.min.js' %} "></script>
    <script src="{% static 'assets/lib/waypoints/waypoints.min.js' %} "></script>
    <script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %} "></script>

    <!-- Template Javascript -->
    <script src="{% static 'assets/js/main.js' %} "></script>
</body>

</html>

templates/real_estate/main/one_property.html
{% extends 'real_estate/main/index.html' %}
{% load i18n %}
{% load static %}
{% block titlePage %}{% translate 'Riyadh Oasis |' %} {{ getOneProperty.title_property }} {% endblock %}
{% block content %}

    <!-- Header Start -->
    <div class="container-fluid header bg-white p-1">
        <div class="row g-0 align-items-center flex-column-reverse flex-md-row" style="margin-top: 120px;">
            <div class="col-md-6">
                <h1>{{ getOneProperty.title_property }}</h1>
                <table class="table">
                    <tbody>
                    <tr>
                        <th scope="row">{% translate 'Country' %}</th>
                        <td>{{ getOneProperty.country_property }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'City' %}</th>
                        <td>{{ getOneProperty.city_property }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'Property Type' %}</th>
                        <td>{{ getOneProperty.property_type }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'Size' %}</th>
                        <td>{{ getOneProperty.size_property }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'Beds ' %}</th>
                        <td>{{ getOneProperty.beds_property }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'Bath' %}</th>
                        <td>{{ getOneProperty.bath_property }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'Price' %}</th>
                        <td>{{ getOneProperty.price_property }}</td>
                    </tr>
                    <tr>
                        <th scope="row">{% translate 'Description' %}</th>
                        <td>{{ getOneProperty.location_property }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6 animated fadeIn" dir="ltr">
                <div class="owl-carousel header-carousel">
                    {% for getAllImage in getAllImagesProperty %}
                        <div class="owl-carousel-item">
                            <img class="" src="{{ getAllImage.images_property.url }} " width="100" height="550" alt="">
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <div class="row">

    </div>

{% endblock %}

templates/real_estate/navbar/navbar.html
{% load i18n %}
{% load static %}
<!-- Spinner Start -->
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">{% translate 'Loading...' %}</span>
    </div>
</div>
<!-- Spinner End -->


<!-- Navbar Start -->
<div class="container-fluid nav-bar bg-transparent" dir="ltr">
    <nav class="navbar navbar-expand-lg nav-bar-background-color navbar-light py-0 px-4">
        <a href="{% url 'real_estate:main_home' %}" class="navbar-brand d-flex align-items-center text-center">
            <div class="p-2 ">
                <img class="img-fluid" src="{% static 'assets/img/logo/logo_riyadh_oasis.png' %} " alt="Icon"
                     style="width: 90px; height: 90px;">
            </div>
            <h1 class="m-0 text-white">{% translate 'Riyadh Oasis' %}</h1>
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto">
                <a href="{% url 'real_estate:main_home' %}" class="nav-item nav-link active">{% translate 'Home' %}</a>
                <a href="#about" class="nav-item nav-link">{% translate 'About' %}</a>
                <!--<div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Property</a>
                    <div class="dropdown-menu rounded-0 m-0">
                        <a href="property-list.html" class="dropdown-item">Property List</a>
                        <a href="property-type.html" class="dropdown-item">Property Type</a>
                        <a href="property-agent.html" class="dropdown-item">Property Agent</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu rounded-0 m-0">
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        <a href="404.html" class="dropdown-item">404 Error</a>
                    </div>
                </div>-->
                <a href="#contact" class="nav-item nav-link">{% translate 'Contact' %}</a>
                <li class="nav-item dropdown">
                    <a class="nav-link bi bi-globe" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                         {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                        {% for lang in languages %}
                            <li>
                                <a style="font-size: 20px;" class="dropdown-item text-black fw-bold"
                                   href="/{{ lang.code }}/">
                                    {{ lang.name_local }}
                                </a>
                            </li>
                        {% endfor %}

                    </ul>
                </li>

            </div>
            <a href="#property_list" class="btn btn-background-color-gold px-3 d-none d-lg-flex">{% translate 'Show Property List' %}</a>
        </div>
    </nav>
</div>
<!-- Navbar End -->